### ISSUE TITLE
Users datatable not loaded

### ISSUE THREAD

**Issue by ihsanberahim** [nasrulhazim/arch#9]
![image](https://user-images.githubusercontent.com/1956846/66975532-59fb8e00-f0d1-11e9-933c-ab17a50fe87b.png)

## Description
i just missing guide to be included in the readme.

## Expected Behavior
Users datatable loaded

## Actual Behavior
Users datatable not loaded

## Possible Fix
Run `php artisan passport:install`

## Steps to Reproduce

1. `composer create-project nasrulhazim/arch project-name --prefer-dist --ignore-platform-reqs`
2. `php artisan key:generate`
3. `php artisan reload:db`
4. `php artisan seed:dev`
5. go to `/users` and `oauth-public.key` does not exist

## Context
I just browse the user list

## Your Environment
* Version used: 2.2.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10 Pro
* Link to your project: N/A

**Comment by nasrulhazim** [comment]
Yes correct, have Passport installed in the Arch. You need to run `php artisan passport:install` after `php artisan reload:db`

**Comment by ihsanberahim** [comment]
Orait. Just not sure how to help include it the readme.

**Comment by nasrulhazim** [comment]
Actually there is bash script to initialise the project - https://github.com/nasrulhazim/arch/blob/master/bin/init.sh

But the a little constraint is you have to set the database connection details before run the `reload:db` and the consequences command.

**Comment by nasrulhazim** [comment]
in readme, after creating project, can provide steps to initialise the application by running `bin/init.sh`

**Comment by ihsanberahim** [comment]
Oh. Actually already give those kick start commands in the bash files. 
Orait. Thanks.
